apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: davidalkobi/nodeapp:1.0.9
        ports:
        - containerPort: 5000
        env:
        - name: USER_NAME
          valueFrom: 
            configMapKeyRef: 
             name: mongodb-config
             key: MONGO_INITDB_ROOT_USERNAME
        - name: USER_PWD
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: DB_URL
          value: mongodb
        - name: mongo_url
          value: mongodb://${process.env.USER_NAME}:${process.env.USER_PWD}@${process.env.DB_URL}
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: myapp
  ports:
  - port: 5000
    targetPort: 5000



