apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            configMapKeyRef: 
              name: mongodb-config
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
       
        ports:
        - containerPort: 27017
        

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
     app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_INITDB_ROOT_USERNAME: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=

